In [13]:
import pandas as pd
import random

In [14]:
folder = '/Users/jakobtjurlik/Library/CloudStorage/OneDrive-Personal/Desktop/Study/MSc_Tilburg/MSc Thesis/code/Models/convlstm'
inputfile = 'test_preds_convlstm.csv'

In [15]:
test= pd.read_csv(folder + '/' + inputfile)

In [16]:
test.head()

,cell_id,actual_1,predicted_1,anomaly_1,actual_2,predicted_2,anomaly_2,actual_3,predicted_3,anomaly_3,...,anomaly_21,actual_22,predicted_22,anomaly_22,actual_23,predicted_23,anomaly_23,actual_24,predicted_24,anomaly_24
0,599_1_1,-105.53,-105.953610,0,-105.53,-105.94141,0,-105.75,-105.943954,0,...,0,-101.68,-106.008080,0,-104.62,-106.038025,0,-105.08,-106.03333,0
1,599_1_1,-105.53,-105.713820,0,-105.75,-105.70192,0,-105.63,-105.709340,0,...,0,-104.62,-105.934840,0,-105.08,-105.971320,0,-104.62,-105.97423,0
2,599_1_1,-105.75,-105.599180,0,-105.63,-105.58629,0,-105.30,-105.594950,0,...,0,-105.08,-105.895200,0,-104.62,-105.935120,0,-102.87,-105.94168,0
3,599_1_1,-105.63,-105.720810,0,-105.30,-105.70628,0,-105.18,-105.711680,0,...,0,-104.62,-105.943756,0,-102.87,-105.981150,0,-102.52,-105.98466,0
4,599_1_1,-105.30,-105.710434,0,-105.18,-105.69754,0,-105.30,-105.705880,0,...,0,-102.87,-105.960000,0,-102.52,-105.996290,0,-100.48,-105.99977,0

In [17]:
def anonymize_cells(folder, inputfile):
    # Load the file
    predictions_df = pd.read_csv(folder + '/' + inputfile)
    
    # Create a mapping for prefixes to new identifiers
    mapping = {}

    def get_new_identifier(cell):
        # Remove underscores and map the fifth and seventh elements
        elements = cell.split('_')  # Split by underscores
        prefix, fifth, seventh = elements[0], elements[1], elements[2]
        
        # Assign random numbers for prefixes if not already mapped
        if prefix not in mapping:
            mapping[prefix] = ''.join(random.choices('0123456789', k=2))
        
        # Convert numeric values to corresponding letters
        fifth_mapped = chr(ord('a') + int(fifth))
        seventh_mapped = chr(ord('a') + int(seventh))
        
        # Construct the new anonymized ID
        new_id = mapping[prefix] + fifth_mapped + seventh_mapped
        return new_id
    
    # Apply the transformation to the `cell_id` column
    predictions_df['cell_id'] = predictions_df['cell_id'].apply(get_new_identifier)
    return predictions_df

# Example usage
anonymized_df = anonymize_cells(folder, inputfile)
anonymized_df

,cell_id,actual_1,predicted_1,anomaly_1,actual_2,predicted_2,anomaly_2,actual_3,predicted_3,anomaly_3,...,anomaly_21,actual_22,predicted_22,anomaly_22,actual_23,predicted_23,anomaly_23,actual_24,predicted_24,anomaly_24
0,31bb,-105.53,-105.953610,0,-105.53,-105.94141,0,-105.75,-105.943954,0,...,0,-101.68,-106.008080,0,-104.62,-106.038025,0,-105.08,-106.03333,0
1,31bb,-105.53,-105.713820,0,-105.75,-105.70192,0,-105.63,-105.709340,0,...,0,-104.62,-105.934840,0,-105.08,-105.971320,0,-104.62,-105.97423,0
2,31bb,-105.75,-105.599180,0,-105.63,-105.58629,0,-105.30,-105.594950,0,...,0,-105.08,-105.895200,0,-104.62,-105.935120,0,-102.87,-105.94168,0
3,31bb,-105.63,-105.720810,0,-105.30,-105.70628,0,-105.18,-105.711680,0,...,0,-104.62,-105.943756,0,-102.87,-105.981150,0,-102.52,-105.98466,0
4,31bb,-105.30,-105.710434,0,-105.18,-105.69754,0,-105.30,-105.705880,0,...,0,-102.87,-105.960000,0,-102.52,-105.996290,0,-100.48,-105.99977,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176112,29ab,-102.94,-103.664420,0,-103.57,-103.62751,0,-105.09,-103.541380,0,...,0,-104.88,-102.611400,0,-106.80,-102.661290,0,-107.22,-102.63782,0
176113,29ab,-103.57,-103.072365,0,-105.09,-103.05316,0,-103.52,-103.022484,0,...,0,-106.80,-103.104800,0,-107.22,-103.172930,0,-106.93,-103.18629,0
176114,29ab,-105.09,-103.551370,0,-103.52,-103.53725,0,-102.14,-103.541270,0,...,0,-107.22,-104.059525,0,-106.93,-104.119280,0,-107.55,-104.14229,0
176115,29ab,-103.52,-104.820350,0,-102.14,-104.81197,0,-101.89,-104.822630,0,...,0,-106.93,-104.961550,0,-107.55,-104.989100,0,-107.40,-104.98571,0
176116,29ab,-102.14,-104.341576,0,-101.89,-104.35103,0,-102.77,-104.398740,0,...,0,-107.55,-105.105690,0,-107.40,-105.137730,0,-107.56,-105.14954,0

In [18]:
anonymized_df.to_csv(inputfile, index=False)