In [48]:
import pandas as pd
import random

In [49]:
folder = '/Users/jakobtjurlik/Library/CloudStorage/OneDrive-Personal/Desktop/Study/MSc_Tilburg/MSc Thesis/code/radio-signal-anomalies'
inputfile = 'test_preds_cnn_multi1.csv'

In [50]:
test= pd.read_csv(folder + '/' + inputfile)

In [51]:
test.head()

,cell_id,actual_1,predicted_1,anomaly_1,actual_2,predicted_2,anomaly_2,actual_3,predicted_3,anomaly_3,...,anomaly_21,actual_22,predicted_22,anomaly_22,actual_23,predicted_23,anomaly_23,actual_24,predicted_24,anomaly_24
0,262_1_0,-103.23,-102.75729,0,-103.18,-102.937780,0,-103.77,-102.962814,0,...,0,-101.80,-102.361244,0,-102.61,-102.303630,0,-101.83,-102.26016,0
1,262_1_0,-103.18,-102.88622,0,-103.77,-103.063950,0,-103.80,-103.094986,0,...,0,-102.61,-102.358420,0,-101.83,-102.300980,0,-102.16,-102.25422,0
2,262_1_0,-103.77,-102.84446,0,-103.80,-103.038970,0,-104.13,-103.068200,0,...,0,-101.83,-101.947030,0,-102.16,-101.874960,0,-102.08,-101.81814,0
3,262_1_0,-103.80,-103.19979,0,-104.13,-103.375114,0,-104.05,-103.408104,0,...,0,-102.16,-102.253120,0,-102.08,-102.175550,0,-102.40,-102.10330,0
4,262_1_0,-104.13,-103.36367,0,-104.05,-103.532820,0,-103.86,-103.555660,0,...,0,-102.08,-102.426670,0,-102.40,-102.346054,0,-102.23,-102.26328,0

In [52]:
def anonymize_cells(folder, inputfile):
    # Load the file
    predictions_df = pd.read_csv(folder + '/' + inputfile)
    
    # Create a mapping for prefixes to new identifiers
    mapping = {}

    def get_new_identifier(cell):
        # Remove underscores and map the fifth and seventh elements
        elements = cell.split('_')  # Split by underscores
        prefix, fifth, seventh = elements[0], elements[1], elements[2]
        
        # Assign random numbers for prefixes if not already mapped
        if prefix not in mapping:
            mapping[prefix] = ''.join(random.choices('0123456789', k=2))
        
        # Convert numeric values to corresponding letters
        fifth_mapped = chr(ord('a') + int(fifth))
        seventh_mapped = chr(ord('a') + int(seventh))
        
        # Construct the new anonymized ID
        new_id = mapping[prefix] + fifth_mapped + seventh_mapped
        return new_id
    
    # Apply the transformation to the `cell_id` column
    predictions_df['cell_id'] = predictions_df['cell_id'].apply(get_new_identifier)
    return predictions_df

# Example usage
anonymized_df = anonymize_cells(folder, inputfile)
anonymized_df

,cell_id,actual_1,predicted_1,anomaly_1,actual_2,predicted_2,anomaly_2,actual_3,predicted_3,anomaly_3,...,anomaly_21,actual_22,predicted_22,anomaly_22,actual_23,predicted_23,anomaly_23,actual_24,predicted_24,anomaly_24
0,52ba,-103.23,-102.757290,0,-103.18,-102.937780,0,-103.77,-102.962814,0,...,0,-101.80,-102.361244,0,-102.61,-102.303630,0,-101.83,-102.26016,0
1,52ba,-103.18,-102.886220,0,-103.77,-103.063950,0,-103.80,-103.094986,0,...,0,-102.61,-102.358420,0,-101.83,-102.300980,0,-102.16,-102.25422,0
2,52ba,-103.77,-102.844460,0,-103.80,-103.038970,0,-104.13,-103.068200,0,...,0,-101.83,-101.947030,0,-102.16,-101.874960,0,-102.08,-101.81814,0
3,52ba,-103.80,-103.199790,0,-104.13,-103.375114,0,-104.05,-103.408104,0,...,0,-102.16,-102.253120,0,-102.08,-102.175550,0,-102.40,-102.10330,0
4,52ba,-104.13,-103.363670,0,-104.05,-103.532820,0,-103.86,-103.555660,0,...,0,-102.08,-102.426670,0,-102.40,-102.346054,0,-102.23,-102.26328,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173709,79ba,-90.66,-93.195100,0,-93.25,-94.087685,0,-93.81,-94.438980,0,...,0,-106.73,-97.943960,0,-106.67,-98.414030,0,-106.73,-99.18550,0
173710,79ba,-93.25,-91.237150,0,-93.81,-92.234120,0,-94.89,-92.705536,0,...,0,-106.67,-99.155685,0,-106.73,-99.503235,0,-106.82,-100.14183,0
173711,79ba,-93.81,-93.511116,0,-94.89,-94.272990,0,-94.20,-94.680120,0,...,0,-106.73,-101.200750,0,-106.82,-101.402100,0,-106.90,-101.83244,0
173712,79ba,-94.89,-93.466170,0,-94.20,-94.110650,0,-95.65,-94.468445,0,...,0,-106.82,-102.147190,0,-106.90,-102.382110,0,-106.74,-102.78583,0
173713,79ba,-94.20,-94.667180,0,-95.65,-95.264350,0,-104.18,-95.662950,0,...,0,-106.90,-103.218410,0,-106.74,-103.408830,0,-106.81,-103.75369,0

In [53]:
anonymized_df.to_csv(inputfile, index=False)